package log

import "testing"

func TestError(t *testing.T) {
	Error("func","test")
}
